### ISSUE TITLE
How to add it to my app

### ISSUE THREAD

**Issue by kimrop19** [pythias-io/pympesa#2]
I have been stuck trying to figure out where to add the code you gave in the README but i don't get it can you please help give direction on where to add each piece of code in my app?

**Comment by andkamau** [comment]
Hi @kimrop19 - if you haven't resolved this yet, hit me up on Skype (_andkamau_) and I'll help you get started.

Meanwhile, I'll go ahead and close this issue. Feel free to raise one if you encounter a problem with the code.

**Comment by HenryKenya** [comment]
@andkamau ..won't it be better just to give the way to get started on SKype instead of Skyping?

**Comment by andkamau** [comment]
@HenryKenya Do you have suggestions on how to improve the [Readme](https://github.com/pythias-io/pympesa/blob/master/README.rst)? How can I add clarity?
